version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catinator
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - .local/db:/var/lib/postgresql/data 
    ports:
      - 5433:5432

  adminer:
    image: adminer
    ports:
      - 8083:8080

  backend:
    image: catinator-backend:latest
    volumes:
        - .local/files:/app/files
    ports:
      - 8080:8080
