# server config
server:
  host: ""
  port: "8080"
  debug: true
  public_storage_folder: "/app/files/public"
  swagger_ui_folder: "/app/swagger-ui"
  swagger_api_file_path: "/app/api.yaml"
  jwt_secret: "supersecret"

# database config
db:
  host: "db"
  port: 5432
  user: "postgres"
  db_name: "catinator"
  password: "password"
  # debug: true
  ssl_mode: "disable"
