// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Cat is the predicate function for cat builders.
type Cat func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
